version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"  # Map the container's port 8000 to the host's port 8000
    volumes:
      - .:/app       # Mount the current directory to /app in the container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload