version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"  # Map the container's port 8000 to the host's port 8000
    volumes:
      - .:/app       # Mount the current directory to /app in the container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydatabase  # Set the database connection string

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore-api-db  # The name of your database
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data between container restarts

volumes:
  postgres_data:  # Named volume to store PostgreSQL data